# Generated by Django 3.2.9 on 2021-11-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
